#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""Guard: the tracked generated governance views must equal what the generator renders.

`docs/governance/{STATUS.md,OWNER_STATUS.md,ASSURANCE_STATUS.yaml}` are DERIVED -- generated by
`scripts/generate_governance_dashboard.py --write` from the canonical machine sources
(delivery_tasks.yaml, development_events.jsonl, VERSION_MATRIX.yaml, ...). They are not files to
hand-edit.

Why this guard exists: the only drift check that compares them against the generator lives in
`.github/workflows/project-governance.yml` ("Verify generated governance dashboard") and is gated on
`github.event_name == 'schedule' || (workflow_dispatch && scope == 'all')`. It does NOT run on push.
So a hand-edited or stale STATUS.md sails through push CI and only turns the NIGHTLY run red -- a red
that lands on whoever happens to look next, detached from the change that caused it. That is the same
failure mode `test_adp_canonical_governance_oids.py` was written for ("a red only visible by reading
CI logs ... make the failure nameable BEFORE the push"), and the same one that made the T088-onward
OID misses invisible for so long.

Scope: every project in `governance/projects.yaml` whose views the generator renders (frozen legacy
views are skipped, as the generator itself skips them). Today that is `arxiv-daily-push` alone --
KMFA / KM_IDSystem / OpenAIDatabase / PFI were migrated out of this repository in the wave-6 split.

The one way this could still hand out a false green -- the generator quietly ceasing to render one of
the three views, leaving the file hand-maintained while this guard passes vacuously -- is asserted
against explicitly below.

Known live defect this guard does NOT paper over: `generate_governance_dashboard.py --write --all`
currently dies with `UnboundLocalError: local variable 'selected' referenced before assignment` in
`select_projects()`, on a pristine origin/main -- i.e. fallout from the wave-6 split, not from ADP.
That matters here twice over: it is the exact command the nightly "Verify generated governance
dashboard" CI step runs, and it fails so early that it writes nothing, so "run it and see no diff"
LOOKS like the views are in sync when nothing was ever rendered. This guard renders in-process
instead, so it cannot be fooled that way. Use `--write --project <id>` until `--all` is repaired.

This renders in-memory and asserts equality. It never writes, so it cannot "fix" drift into existence.
"""
import importlib.util
import pathlib
import sys
import unittest

ROOT = pathlib.Path(__file__).resolve().parents[2]
GENERATOR = ROOT / "scripts" / "generate_governance_dashboard.py"


def _load_generator():
    # The generator imports its siblings by bare name (`import validate_project_governance`), so
    # scripts/ must be importable -- same loader shape the other governance tests use.
    scripts_dir = str(ROOT / "scripts")
    if scripts_dir not in sys.path:
        sys.path.insert(0, scripts_dir)
    spec = importlib.util.spec_from_file_location("governance_dashboard_for_view_drift", GENERATOR)
    module = importlib.util.module_from_spec(spec)
    sys.modules[spec.name] = module
    spec.loader.exec_module(module)
    return module


class TestGeneratedProjectViewsMatchGenerator(unittest.TestCase):
    @classmethod
    def setUpClass(cls):
        cls.gen = _load_generator()
        # Mirror generate()'s own project discovery so this guard cannot drift from what it checks.
        config = cls.gen.structural.load_yaml(cls.gen.structural.PROJECTS_FILE)
        cls.projects = [p for p in cls.gen.structural.as_list(config.get("projects")) if isinstance(p, dict)]

    def _live_projects(self):
        """Projects whose views the generator actually renders (frozen legacy views are skipped by it)."""
        live = []
        for project in self.projects:
            path = ROOT / project["path"]
            if not (path / "docs" / "governance").is_dir():
                continue
            if self.gen.legacy_project_views_frozen(path):
                continue
            live.append(project)
        return live

    def test_generator_still_renders_these_three_views(self):
        """If the generator stops rendering one of these paths, the assertions below would pass
        vacuously while the file quietly became hand-maintained. Pin the contract."""
        source = GENERATOR.read_text(encoding="utf-8")
        for name in ("STATUS.md", "OWNER_STATUS.md", "ASSURANCE_STATUS.yaml"):
            self.assertIn(
                name, source,
                "{} is no longer produced by the generator -- this guard would be checking nothing".format(name))

    def test_tracked_views_match_a_fresh_render(self):
        live = self._live_projects()
        self.assertTrue(live, "no project with renderable governance views -- this guard protects nothing")

        drifted = []
        for project in live:
            info = self.gen.load_project(project)
            base = ROOT / info["path"] / "docs" / "governance"
            expected = {
                base / "ASSURANCE_STATUS.yaml": "\n".join(self.gen.dump_yaml(info["assurance"])) + "\n",
                base / "STATUS.md": self.gen.render_status(info),
                base / "OWNER_STATUS.md": self.gen.render_owner_status(info),
            }
            for path, text in expected.items():
                if not path.is_file():
                    drifted.append("{}: MISSING (the generator renders it)".format(path.relative_to(ROOT)))
                    continue
                if path.read_text(encoding="utf-8") != text:
                    drifted.append("{}: differs from a fresh render".format(path.relative_to(ROOT)))

        self.assertEqual(
            drifted, [],
            "Generated governance view(s) do not match the generator. These files are DERIVED -- do not "
            "hand-edit them; edit the canonical sources and run\n"
            "  python3 scripts/generate_governance_dashboard.py --write --all\n"
            "Push CI does NOT catch this (the drift check is schedule/dispatch-only), so it would surface "
            "as a nightly red instead:\n  " + "\n  ".join(drifted))


if __name__ == "__main__":
    unittest.main()
